@startuml
skinparam linetype polyline
left to right direction
hide empty methods
hide empty members
title "Domain Diagram"

' Entities

entity Sport {
  name
  description
}

entity Club {
clubName
location
phoneNumber
clubEmail
workingHours
webSite
}

entity Court {
courtNumber
description
hourlyFee
surfaceType
indoorOutdoor
lightningAvailable
}

entity Client {
name
fiscalID
mail
phoneNumber
address
registerDate

}

entity Employee {
name
role
status
workingHours
fiscalID
mail
clubEmail
phoneNumber
address
}

entity Booking{
date
hour
duration
status
createdAt
canceledAt
}

entity Payment{
method
status
price
timeStamp
paymentReference
}

Sport "*" --> "*" Club
Employee "1" --> "1" Club
Court "1" --> "1" Club
Booking "1" --> "1" Court
Booking "1" --> "1" Client
Booking "1" --> "1" Payment
Court "1" --> "1" Sport


@enduml